server:
  port: 9091
  servlet:
    encoding:
      charset: UTF-8

spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/msa_starter
    driverClassName: com.mysql.cj.jdbc.Driver
    username: msa
    password: password

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  flyway:
    enabled: true
    encoding: UTF-8
    url: jdbc:mysql://localhost:3306
    schemas: msa_starter
    user: msa
    password: password
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

application:
  rest-template:
    connection-timeout: 2000
    read-timeout: 5000
  event-publisher:
    enabled: true